export const lines = [
    {
        text: "Grejanje",
        icon: 'fireplace',
        families: [
            {
                name: "Bakarne cevi",
                groups: [
                    'Bakarne cevi - prave tvrde 5m',
                    'Bakarne cevi - prave polutvrde 5m',
                    'Bakarne cevi - Industrijske',
                    'Bakarne cevi - PVC',
                    'Bakarne cevi - Cu Smart',
                    'Bakarne cevi - Talos Dual',
                    'Neaktivne pozicije',
                ]
            }, 
            {
                name: "Višeslojne i plastične cevi",
                groups: [
                    'Višeslojne i plastične cevi - COMAP', 
                    'Višeslojne i plastične cevi - KAN THERM',
                    'Višeslojne i plastične cevi - WEGA',
                    'Višeslojne i plastične cevi - REHAU',
                    'Višeslojne i plastične cevi - UPONOR',
                    'Višeslojne i plastične cevi - PEŠTAN',
                    'Višeslojne i plastične cevi  - OSTALO',
                ],
            },
            {
                name: "Čelicne cevi",
                groups: [
                    'Čelične cevi (crne)',
                    'Čelične galvanizovane cevi ',
                ],
            },
            {
                name: "Fiting",
                groups: [
                    'Bakarni fiting - EU',
                    'Bakarni fiting - (S)',
                    'Bakarni fiting - (KTM)',
                    'Bakarni fiting - KEPO',
                    'Bakarni pres fiting fiting - IBP',
                    'Mesingani fiting (prelazi) - KOFORM',
                    'Mesingani fiting (prelazi) - UVOZ',
                    'Mesingani fiting (prelazi) - RAZNO',
                    'Bronzani fiting',
                    'Bronzani fiting - VIEGA',
                    'Pres fiting - COMAP',
                    'Pres fiting - IBP',
                    'PRES FITING - UPONOR',
                    'Pres fiting - RAZNO',
                    'Kompresioni fiting - COMAP',
                    'Kompresioni fiting - KINA',
                    'Kompresioni fiting Cu - Jevco',
                    'Kompresioni fiting - TIEMME',
                    'Kompresioni fiting - STRATO PLUS',
                    'Galvanizovani fiting',
                    'Čelični fiting (crni)',
                    'Čelični fiting crni - RAZNO',
                    'Neaktivne pozicije',
                    'Radijatorski ventili  i oprema - COMAP',
                ],
            },
            {
                name: "Armatura",
                groups: [
                    'Radijatorski ventili  i oprema - COMAP',
                    'Termostatski setovi  - COMAP',
                    'Radijatorski ventili i oprema - HEIMEIER',
                    'Termostatski setovi  - HEIMEIER',
                    'Radijatorski ventili i oprema  - CALEFFI',
                    'Radijatorski ventili i oprema  - KRT DELFIN',
                    'Radijatorski ventili i oprema  - HERZ',
                    'Radijatorski ventili i oprema  - OVENTROP',
                    'Radijatorski ventili i oprema  - TIEMME',
                    'Radijatorski ventili i oprema  - RAZNO',
                    'Regulacioni ventili Ballorex – COMAP',
                    'Ventili i slavine - IBP',
                    'Ventili i slavine - LD',
                    'Ventili i slavine - SLOVARM',
                    'Ventili i slavine - FERRO',
                    'Ventili i slavine - AQUAWORLD',
                    'Ventili i slavine - RAZNO',
                    'Mešni i elektromotorni ventili, pogoni - ESBE',
                    'Mešni i elektromotorni ventili, pogoni - RAZNO',
                    'Oprema za čišćenje i odzračivanje',
                ],
            },
            {
                name: "Oprema za podno grejanje",
                groups: [
                    'Oprema za podno grejanje Biofloor - COMAP',
                    'Oprema za podno grejanje - REHAU',
                    'Oprema za podno grejanje  - POLY',
                    'Oprema za podno grejanje  - UPONOR',
                    'Mesingani razdelnici i dodatna oprema - COMAP',
                    'Oprema za podno grejanje - ITAP',
                    'Oprema za podno grejanje - RAZNO',
                    'Ormarići za razdelnike - TERMOPOOL',
                    'Oramrići za razdelnike - RAZNO',
                    'Oprema za podno grejanje - KAN THERM',
                    'Ploča za podno grejanje',
                ],
            },
            {
                name: "Kotlovi",
                groups: [
                    'Kotlovi - RADIJATOR INŽENJERING',
                    'Kotlovi - RADIJATOR INŽENJERING - Industrijski',
                    'Kotlovi - KEPO',
                    'Kotlovi - ALFA PLAM',
                    'Kotlovi - MEGAL',
                    'Kotlovi - ENRAD',
                    'Kotlovi - CENTROMETAL',
                    'Kotlovi - EKOTERM PROEKT',
                    'Kotlovi - TERMOMONT',
                    'Kotlovi - THERMOFLUX',
                    'Kotlovi - ŠUKOM',
                    'Kotlovi - MARELI',
                    'Kotlovi - PRITY',
                    'Kotlovi - ABC',
                    'Kotlovi - BLIST',
                    'Kotlovi - KEPO WOOD',
                    'Kotlovi - RAZNO',
                    'Liveni Kotlovi - VIADRUS',
                    'Liveni kotlovi - FERROLI',
                    'Liveni kotlovi - LOGAN',
                    'Električni kotlovi - EKOPAN DM',
                    'Električni kotlovi - MIKOTERM',
                    'Električni kotlovi - VAILLANT',
                    'Električni kotlovi - VIESSMANN',
                    'Električni kotlovi - IMPRO',
                    'Električni kotlovi - TRGOELEKTR0',
                    'Električni kotlovi - EKOPAN DM (Izvoz)',
                    'Gasni kotlovi - VAILLANT',
                    'Gasni kotlovi - ARISTON',
                    'Gasni kotlovi - VIESSMANN',
                    'Gasni kotlovi - PROTHERM',
                    'Gasni kotlovi - IMMERGAS',
                    'Gasni kotlovi - OSTALO',
                    'Neaktivne pozicije',
                ],
            },
            {
                name: "Rezervni delovi i dodatna oprema za kotlove",
                groups: [
                    'Rezervni delovi i oprema za kotlove - RADIJATOR INŽENJERING',
                    'Rezervni delovi i oprema za kotlove - KEPO',
                    'Rezervni delovi i oprema za kotlove - ALFA PLAM',
                    'Rezervni delovi i oprema za kotlove - MEGAL',
                    'Rezervni delovi i oprema za kotlove - ENRAD',
                    'Rezervni delovi i oprema za kotlove - CENTROMETAL',
                    'Rezervni delovi i oprema za kotlove - EKOTERM PROEKT',
                    'Rezervni delovi i oprema za kotlove - VIADRUS',
                    'Rezervni delovi i oprema za kotlove - EKOPAN DM',
                    'Rezervni delovi i oprema za kotlove - MIKOTERM',
                    'Rezervni delovi i oprema za kotlove - VAILLANT',
                    'Rezervni delovi i oprema za kotlove - ARISTON',
                    'Rezervni delovi i oprema za kotlove - VIESSMANN',
                    'Rezervni delovi i oprema za kotlove - PROTHERM',
                    'Rezervni delovi i oprema za kotlove -IMMERGAS',
                    'Rezervni delovi i oprema za kotlove - RAZNO',
                    'Pretvarači napona - MIK',
                    'Pretvarači napona - MC',
                    'Regulatori promaje',
                    'Dodatna oprema i pribor za kotlove',
                    'Vatrostalne opeke',
                    'Upaljači za pelet - IEG',
                    'Kotlovski razdelnici i hidraulične skretnice - MIK MARING',
                    'Kotlovski razdelnici i hidraulične skretnice - MEIBES',
                    'Dodatna oprema i pribor za kotlove - RAZNO',
                    'Dodatna oprema za gasne kotlove - RAZNO',
                ],
            },
            {
                name: "Antifriz",
                groups: [
                    'Antifriz - ADECO',
                    'Antifriz - N-ANT',
                    'Antifriz - AURORA',
                    'Antifriz - DINARA OIL',
                    'Antifriz - RAZNO',
                ],
            },
            {
                name: "Radijatori",
                groups: [
                    'Radijatori panelni - ENRAD',
                    'Radijatori panelni - IMAS',
                    'Radijatori panelni - TERMOPAN',
                    'Radijatori panelni - PURMO',
                    'Radijatori panelni - RAZNO',
                    'Radijatori aluminijumski - GLOBAL',
                    'Radijatori aluminijumski - FERROLI',
                    'Radijatori aluminijumski - FARAL',
                    'Radijatori aluminijski - RAZNO',
                    'Radijatori cevasti - EURO',
                    'Radijatori cevasti - ENRAD',
                    'Radijatori cevasti - STARPAN',
                    'Radijatori cevasti - M&A',
                    'Radijatori cevasti - TERMAL TREND',
                    'Radijatori cevasti - ELEGANT',
                    'Radijatori cevasti - CINI',
                    'Radijatori cevasti - RAZNO',
                    'Neaktivne pozicije',
                ],
            },
            {
                name: "Dodatna oprema za radijatore",
                groups: [
                    'Dodatna oprema za radijatore',
                    'Dodatna oprema za radijatore - KRT DELFIN',
                    'Grejači za radijatore - IEG',
                    'Grejači za radijatore - CINI',
                    'Neaktivne pozicije',
                ],
            },
            {
                name: "Pumpe",
                groups: [
                    'Pumpe cirkulacione - WILO',
                    'Pumpe - GRUNDFOS',
                    'Pumpe - IMP',
                    'Pumpe - HST',
                    'Pumpe - WRS',
                    'Pumpe - Unacl',
                    'Pumpe - RAZNO',
                    'Pumpe OEM - WILO',
                    'Pumpne grupe - MEIBES',
                    'Pumpne grupe - ICMA',
                    'Pumpne grupe - HERZ',
                    'Pumpe - Pribor - RAZNO',
                    'Neaktivne pozicije',
                ],
            },
            {
                name: "Oprema za kotlarnice i podstanice",
                groups: [
                    'Armatura za kotlarnice i podstanice',
                    'Ventili - sigurnosni',
                    'Hidraulične skretnice, razdelnici i pribor',
                    'Kalorimetri',
                    'Pumpne stanice',
                    'Izmenjivači toplote',
                    'Toplotne podstanice',
                ],
            },
            {
            name: "Pribor za fiksiranje i kačenje",
            groups: [
                'Šrafovska roba - OSTALO',
            ],
            },
            {
            name: "Izolacije",
            groups: [
                'Izolacija mineralna vuna',
                'Dekorativna izolacija - HZ',
                'Neaktivne pozicije',
                'Izolacija cevi',
            ],
            },
            {
                name: "Ekspanzione posude",
                groups: [
                    'Ekspanzione posude grejačke - BASEFLEX',
                    'Eskpanzione posude grejačke - VAREM',
                    'Ekspanzione posude grejačke - ELBI',
                    'Ekspanzione posude grejačke - AQUASYSTEM',
                    'Ekspanzione posude grejačke - ZAVARIVAČ',
                    'Ekspanzione posude grejačke - PNEUMATEX',
                    'Ekspanzione posude grejačke - TERMORAD',
                    'Ekspanzione posude grejačke - DUKLA',
                    'Ekspanzione posude grejačke - RAZNO',
                    'Pribor za ekspanzione posude',
                ],
            },
            {
                name: "Dimovodne cevi i sistemi",
                groups: [
                    'Dimovodne cevi - KEPO',
                    'Dimovodne cevi - ZAVARIVAČ',
                    'Dimovodne cevi - STANDARD',
                    'Štucne, vrata dimnjaka, ventilacione resetke - ANTIĆ KOSTA',
                    'Dimovodne cevi - BRAVAR',
                    'Dimovodne cevi - ALFA',
                    'Dimovodne cevi za peći na pelet - RAZNO',
                    'Dimovodni sistemi - SCHIEDEL',
                    'Dimovodni sistemi - KEPO',
                    'Dimovodne cevi i sistemi - RAZNO',
                    'Neaktivne pozicije',
                ],
            },
            {
                name: "Merno regulaciona oprema",
                groups: [
                    'Merno regulaciona oprema - KRT',
                    'Merno regulaciona oprema - KINA',
                    'Merno regulaciona oprema - SITEM',
                    'Merno regulaciona oprema - SIEMENS',
                    'Merno regulaciona oprema - RAZNO',
                    'Sobni termostati - KINA',
                    'Sobni termostati - SALUS',
                    'Sobni termostati - RAZNO',
                    'Neaktivne pozicije',
                ],
            },
            {
                name: "Solarni sistemi",
                groups: [
                    'Solarni kolektori - VIESSMANN',
                    'Solarni kolektori - CAMEL SOLAR',
                    'Nosači za solarne kolektore',
                    'Diferencijalni termostati',
                    'Neaktivne pozicije',
                ],
            },
            {
                name: "Toplotne pumpe",
                groups: [
                    'Toplotne pumpe - MITSUBISHI',
                    'Toplotne pumpe - FERROLI',
                    'Toplotne pume - LG',
                    'Toplotne pumpe - VIESSMAN',
                ],
            },
            {
                name: "Akumulacioni rezervoari, bojleri i oprema",
                groups: [
                    'Akumul. rezervoari, bojleri i oprema - RADIJATOR INŽENJERING',
                    'Akumul. rezervoari, bojleri i oprema - CENTROMETAL',
                    'Akumul. rezervoari, bojleri i oprema - BURNIT',
                    'Akumul. rezervoari, bojleri i oprema - BOSCH',
                    'Akumul. rezervoari, bojleri i oprema - RAZNO',
                ],
            },
            {
                name: "Materijal za ogrev",
                groups: [
                    'Pelet',
                ],
            },
        ]
    },
    {
        text: "Vodovod i kanalizacija",
        icon: 'shower',
        families: [
            { 
                name: "Vodovodne cevi i fiting",
                groups: [
                    'PE-X Cevi i fiting - INTERPLAST',
                    'PPR cevi i fiting- VALDOM',
                    'PPR cevi i fiting - PILSA',
                    'PPR cevi i fiting - PEŠTAN',
                    'PPR cevi i fiting - METAPLAST',
                    'PPR fiting - PILSA',
                    'Pocinkovani fiting (KRT) - KINA',
                    'Pocinkovani fiting - TITAN',
                    'Pocinkovani fiting - IBP',
                    'Hromirani fiting',
                    'Hromirani fiting - MINOTTI',
                    'Hromirani fiting',
                    'Gumice i dihtunzi',
                    'Mesingani fiting - DOMAĆI',
                    'Mesingani fiting - KOFORM',
                    'Mesingani fiting - SLOVARM',
                    'Mesingani fiting - RAZNO',
                    'PE-X Cevi i fiting',
                    'Čelične cevi pocinkovane',   
                ],
            },
            { 
                name: "Kanalizacione cevi i fiting",
                groups: [
                    'Kanalizacione cevi i fiting - VALDOM',
                    'Kanalizacione cevi i fiting - PEŠTAN',
                    'Kanalizacione cevi i fitin - RAZNO',
                    'Drenažna creva',
                ],
            },
            { 
                name: "Okiten creva i armatura",
                groups: [
                    'Okiten creva - VALDOM',
                    'Okiten creva - RAZNO',
                    'Fiting za okiten - VALDOM',
                    'MS fiting za okiten',
                    'Fiting za okiten - UNIDELTA',
                    'Fiting za okiten - FERMESKOP',    
                ],
            },
            { 
                name: "Sanitarije",
                groups: [
                    'Vodokotlići i pribor',
                    'WC šolje, pisoari i pribor',
                    'SLIVNICI I REŠETKE',
                    'Priključna creva armirana',
                    'Priključna creva - RAZNO',
                    'Sifoni i pribor',
                ],
            },
            { 
                name: "Pumpe za transport hladne i sanitarne vode",
                groups: [
                    'Pumpe za transport hladne i sanitarne vode - WILO',
                    'Pumpe za transport hladne i sanitarne vode - PEDROLLO',
                    'Pumpe za transport hladne i sanitarne vode - NOVOTERM PRO',
                    'Pumpe za transport hladne i sanitarne vode - RAZNO',
                    'Hidrofori i pribor',
                    'Pribor za pumpe za transport hladne vode',
                ],
            },
            { 
                name: "Hidroforske i sanitarne ekspanzione posude",
                groups: [
                    'Eskpanzione posude sanitarne - AQUASYSTEM',
                    'Ekspanzione posude sanitarne - VAREM',
                    'Ekspanzione posude sanitarne - ELBI',
                    'Ekspanzione posude sanitarne - RAZNO',
                    'Hidroforske posude -TERMORAD',
                    'Hidroforske posude -AQUASYSTEM',
                ],
            },
            { 
                name: "Vodovodna armatura",
                groups: [
                    'Vodovodna armatura - STRATO PLUS',
                    'Vodovodni ventili - SLOVARM',
                    'Vodovodna armatura - FERMES',
                    'Vodovodna armatura - VALVEX',
                    'Vodovodna armatura - ITAP',
                    'VODOVODNA ARMATURA - RAZNO',
                    'Virble',
                    'Spojnice reparacione',
                ],
            },
            { 
                name: "Baštenska creva i armatura",
                groups: [
                    'Baštenska creva',
                    'Baštenske slavine - IBP',
                    'Baštenske slavine - RAZNO',
                    'Spojnice',
                    'Prskalice i mlaznice',
                ],
            },
            { 
                name: "Bojleri i izmenjivači toplote",
                groups: [
                    'Bojleri - TERMORAD',
                    'Bojleri - ELIT INOX',
                    'Bojleri - TERMIL',
                    'Bojleri - GORENJE',
                    'Bojleri - ELMAC',
                    'Bojleri - TESY',
                    'Bojleri - METALAC',
                    'Bojleri - INOX-PRERADA',
                    'BOJLERI - EGV',
                    'Bojleri - DRAŽICE',
                    'Bojleri - RAZNO',
                    'Rezervni delovi za bojlere - TERMORAD',
                    'Oprema za bojlere',
                    'Grejači za bojlere - IEG',
                    'Grejači - RAZNO',
                    'Izmenjivači toplote',
                ],
            },
            { 
                name: "Baterije tuševi i pribor",
                groups: [
                    'Baterije, tuševi i pribor - CLEVER',
                    'Baterije, tuševi i pribor - MINOTTI',
                    'Baterije, tuševi i pribor - FIORE',
                    'Baterije, tuševi i pribor - SLOVARM',
                    'Baterije, tuševi i pribor - KOMAK',
                    'Baterije, tuševi i pribor - RAZNO',
                    'Delovi za tuševe i baterije',
                    'Pribor za tuševe i baterije',
                ],
            },
            { 
                name: "Oprema za kupatila",
                groups: [
                    'Kade i lavaboi',
                    'Pribor i delovi za kade i lavaboe',
                    'Kupatilski nameštaj',
                    'Tuš kabine',
                    'Ventilatori - Antić Kosta',
                    'Ventilatori - TEXO ELITE',
                    'Galanterija i oprema za kupatilo',
                    'Neaktivne pozicije',
                ],
            },
            { 
                name: "Vodomeri, hidranti i pribor",
                groups: [
                    'Vodomeri i pribor',
                    'Hidranti i pribor',
                ],
            },
            { 
                name: "Prečišćavanje i omekšavanje vode",
                groups: [
                    'Filteri i pribor - KOMEO',
                    'Filteri i pribor - RAZNO',
                ],
            },
        ],
    },
    {
        text: "Klimatizacija",
        icon: 'ac_unit',
        families: [
            {
                name: "Bakarne cevi - EN12735",
                groups: [
                    'Bakarne cevi odmašćene - prave tvrde 5m',
                    'Bakarne cevi - u koturu',
                    'Bakarne cevi - izolovane',
                ],
            },
            {
                name: "Klima uređaji",
                groups: [
                    'Klima uređaji - VIVAX',
                    'Klima uređaji - GREE',
                    'Klima uređaji - MIDEA',
                    'Klima uređaji - HISENSE',
                    'Klima uređaji - VEISSMAN',
                    'Klima uređaji - LG',
                    'Klima uređaji VOX',
                    'Oprema za klima uređaje',
                    
                ],
            },
            {
                name: "Fan coil uređaji",
                groups: [
                    'Fan coil uređaji - SABIANA',
                    'Fan coil uređaji - MIDEA',
                    'Fan coil uređaji - PROTEAN',
                    'Fan coil uređaji - OLIMPIA SPLENDID',
                    'Fan coil uređaji - GALLETTI ESTRO',
                    'Oprema za fan coil uređaje',
                    
                ],
            },
            {
                name: "Ventilacija",
                groups: [
                    'Grejalice na struju',
                    'Kaloriferi i pribor',
                    'Ventilatori',
                    'Radijatori',
                ],
            }
        ]
    },
    {
        text: "Alati i pribor",
        icon: 'construction',
        families: [
            {
                name: 'Alati i pribori',
                groups: [
                    'Alati - ROTHENBERGER',
                    'Alati - REMS',
                    'Alat za Al-Pex',
                    'Alat za domaćinstvo - RAZNO',
                    'Zaštitna oprema',
                ],
            },
            {
                name: 'Pribor za fiksiranje i kačenje',
                groups: [
                    'Pribor za fiksiranje i kačenje - FISCHER',
                    'Pribor za fiksiranje i kačenje - OSTALO',
                    'Metalne šelne',
                    'Šelne za creva',
                    'PVC šelne i rozetne - POLY',
                ]
            },
            {
                name: "Pribor za lemljenje, zavarivanje i zaptivanje",
                groups: [
                    'Pribor za lemljenje, zavarivanje i zaptivanje - FELDER',
                    'Pribor za lemljenje, zavarivanje i zaptivanje - HENKEL',
                    'Pribor za lemljenje, zavarivanje i zaptivanje - RAZNO',
                    'Gas MAPP',
                    'Teflon',
                    'Silikon',
                    'Pur pena',
                ]
            }
        ],
    },
];